### PR TITLE
alias support - fixes #30 

### LINKED ISSUE #30: support references
We at tutory use references to other translations for translations from time to time.

we build this preprocessor for this:

```
function replaceReference(translation) {
  if (isObject(translation)) {
    return replaceReferences(translation);
  }
  return translation.replace(/{{(.*)}}/, function(_, key) {
    if (translations[key] == null) {
      throw new Error('Unable to find translation for placeholder "' + key + '"');
    }
    return replaceReference(translations[key]);
  });
}

function replaceReferences(translations) {
  return mapValues(translations, replaceReference);
}

translations = replaceReferences(translations);
```

It basically replaces all `{{translationKey}}` in the translation with the translation of the appropriate translation. This could be used for aliases and for embedding of translation into one another.

This could well live is userland but it might also helpful for others.

What do you think?

### PR DESCRIPTION
**Pull request by StephanHoyer**

### CODE REVIEW

**Comment by StephanHoyer** [comment]
@maranomynet plz review an merge if you are ok with it.

I'll do a release then.

**Comment by maranomynet** [comment]
Should the order of keys in the translations object matter?

i.e. should this test pass?

```js
it('should be agnostic to the order of key declarations', function () {
  expect(translate.resolveAliases({
    C: '< {{B}} >',
    B: 'foo {{A}} bar',
    A: 'bar',
  })).to.eql(translate.resolveAliases({
    A: 'bar',
    B: 'foo {{A}} bar',
    C: '< {{B}} >',
  }))
})
```

Supporting this would require a slightly more complicated resolution algorithm, but not that much.

**Comment by maranomynet** [comment]
It seems that the circular reference detection isn't only detecting circular references.

**Comment by maranomynet** [comment]
Also, I would have expected this test to pass:

```js
it('should allow multiple aliases per string', function () {
  expect(translate.resolveAliases({
    A: 'bar',
    B: 'foo {{A}} {{A}}',
    C: 'foo {{B}} {{A}}'
  })).to.eql({
    A: 'bar',
    B: 'foo bar bar',
    B: 'foo foo bar bar bar'
  })
})
```

**Comment by maranomynet** [comment]
I pushed the tests just in case... feel free to revert aaebaad if you think either of these is unreasonable or unnecessary atm.

**Comment by StephanHoyer** [comment]
Thanks.

Just tried to fix this... not trivial.

**Comment by StephanHoyer** [comment]
ok, just found a simple solution. Feel free to check again

**Comment by maranomynet** [comment]
Looks great. I can't think of any other missing features.

**Pull request merged**
