### PR TITLE
Vdom awareness - fixes #19

### LINKED ISSUE #19: Add vdom awarness
Would be great to allow something like this
```javascript
t = translate({
  foo: 'bar {baz} foz'
})

t('foo', {
  baz: m('img', {}) //
})
// result: ['bar ', m('img', {}), ' foz']
```

@maranomynet what do you think of that?

### PR DESCRIPTION
**Pull request by StephanHoyer**
…des in translations

### CODE REVIEW

**Comment by StephanHoyer** [comment]
@maranomynet what do you think?

**Comment by maranomynet** [comment]
See inline discussion in 71f4732

**Comment by maranomynet** [comment]
BTW, I updated benchmark.html in 74d431b and it shows that with v0.4.0, the performance of replacements basically tanks. :-(
My WIP [feature/array_option branch](/StephanHoyer/translate.js/tree/feature/array_option) improves things a bit, but it's still almost an order of magnitude slower than v0.3.2.
I'm exploring options as to how to get the old performance back.

**Comment by maranomynet** [comment]
I'll add comments on the process in #22

**Pull request merged**
