### PR TITLE
Modernize project

### PR DESCRIPTION
**Pull request by maranomynet**
This converts the main `index.js` file into a plain es6 module (using `export default` only – no big syntax changes yet) and adds minimal build scripts (Rollup.js + Bublé) to spit out a clean CommonJS module and a UMD module for consumption by browsers.

The build scripts are automatically run `prepublish` to double-ensure everything is up-to-date in the npmjs registry.

Additionally this update adds a `npm run dev` script which watches changes in the main `index.js` file and runs the tests on each file save.

* [x] ~~I plan on adding a separate commit where I update the main module to es2015 syntax. (Mainly just `let`, `const` and arrow-functions, nothing too fancy or futuristic.)  
The build scripts will convert those back to old-school `var`s and `function(){}` syntax for the published files.~~

### CODE REVIEW

**Comment by StephanHoyer** [comment]
I just cleaned some stuff up and reduced to only one build (umd) which also works in node and browserify.
If you think the extra bytes are worth it, feel free to readd the cjs-build again.
Also feel free to use modern js where it leads to better readablity. I'm fine with spread and arrow-fn.

I also rebased to current master branch.

I would not like to get yarn stuff in this repo. I still think yarn has to die as fast as possible :D

So feel free to modernize this project further.

**Comment by StephanHoyer** [comment]
Ah, and I add prettier formatting.

**Comment by StephanHoyer** [comment]
I think we can skip buble-stuff. Anyone who targets older browser already had something like that in place I guess.

**Comment by StephanHoyer** [comment]
Is there a way to test that the es6 module export really works? Maybe create a es6-module based test and run it through buble?

**Comment by maranomynet** [comment]
Regarding es6 module test - yes we could make a es6 module-based test and run the whole thing through Rollup - but as the module currently only has a single `default` export, it hardly seems worth the effort.

In fact I'd rather like go in the direction of simplifying the test script by way of changing it to use something super-minimal like [ospec](https://www.npmjs.com/package/ospec)

**Comment by maranomynet** [comment]
Just add `yarn.lock` to `.gitignore` if you like. With a list of dependencies this short, predictable/deterministic installs don't really matter that much.

If I could make a single request regarding Prettier, it would be to add `arrowParens: "always"` to the settings. I've tried loving the whole sporadic function-parameter wrapping thing, but it always makes my head ache. :-)

**Comment by maranomynet** [comment]
> The build scripts are automatically run `prepublish` to double-ensure [...]

I see I failed to include that script - which is probably the reason why you added back the `dist` folder.

If we do add `prepublish` script that formats and builds on both `npm publish` (and local/dev install) then it becomes redundant to commit the built/transpiled contents of the `dist` folder. That way the commit log will be less noisy.

**Comment by StephanHoyer** [comment]
@maranomynet just adapted some things regarding your comments

Replacing mocha would be nice, don't have the time currently. Feel free to do this.
Otherwise I would publish a 1.0 after merging this.

**Pull request merged**
