### PR TITLE
fix plurals

### PR DESCRIPTION
**Pull request by StephanHoyer**

### CODE REVIEW

**Comment by maranomynet** [comment]
These changes are incorrect according to both this list: 
http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html?id=l10n/pluralforms and this info: https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_and_Plurals

**Comment by StephanHoyer** [comment]
It might be wrong. It's e.g. `100 errors`, but `101 error`.

I'm not entirely sure thought

Screenshot 2019-07-21 22 40 01

**Comment by maranomynet** [comment]
https://en.m.wikipedia.org/wiki/101_Dalmatians_(1996_film)

**Comment by maranomynet** [comment]
Also, reading Mozilla's resource and the obscure rules there, it seems highly unlikely that they get either German or English wrong.

**Comment by maranomynet** [comment]
I bet some languages may have special-case pluralization rules/traditions for certain specific words or things, but those will have to be handled on a special-case by special-case basis.

Closing this until perfect certainty has been reached

**Pull request closed without merging**
