### PR TITLE
Expose `messageObject` and options as `.keys` and `.opts`

### PR DESCRIPTION
**Pull request by maranomynet**
This allows for more flexible/light-weight handling of
translation functions, such as:

* Adding more translations incrementally
* Changing locales/languages on the fly
* etc...

### CODE REVIEW

**Comment by maranomynet** [comment]
I personally like the philosophy of keeping thins as simple and transparent as possible.

**Comment by maranomynet** [comment]
oops.

**Comment by StephanHoyer** [comment]
Doesn't this lead to bad style? Exposing translations might be ok, but options should be set only once.

Otherwise it's really hard to reason about, who changes what.

I also see no use-case for doing this. Maybe you can delight me here ;)

**Comment by maranomynet** [comment]
One of the things I wanted to allow was to allow on-the-fly language change in an application (by replacing the translations) and that requires being able to change the pluralization function. (Hence the exposing of `.opts`.)

I guess another method would be to keep the current static behaviour, and make an application always access the translation function through an intermediary factory wrapper.

```js
// texts.js
var translate = require('translate.js');
var t = translate( defaultKeys, defaultOpts );
module.exports = {
    text: () => t,
    change: ( newKeys, pluralizeFn ) => {
        t = translate( newKeys, {
            namespaceSplitter: defaultOpts.namespaceSplitter,
            pluralize: pluralizeFn || defaultOpts.pluralize
        });
    }
};
```

Access: 

```js
// app.js
var texts = require('./texts.js');
var t = texts.t()

alert( t('helloworldMsg') );
```

But, simply exposing the `.keys` and `.opts` seemed like one way to remove the need for factory/getter wrappers, and stay true to the "micro" part of the project description.

It *allows* for bad style, for sure, but doesn't necessarily lead to it.

**Comment by maranomynet** [comment]
I guess there are three main choices:

1. Keep things as is (immutable) to actively prevent messy coding.
2. Make things mutable (accept this PR) and super expressive and trust developers. (Achieve immutability through wrapping).
3. Make only the `.keys` mutable (partial roll-back for these changes) to allow incrementally adding translations to a global pool.

Your call. :-)

**Comment by StephanHoyer** [comment]
have to look this closely... give me another day or two ;)

**Comment by maranomynet** [comment]
I have implemented the getter/wrapper pattern (`module.exports= ()=>t.apply(null,arguments)`) in the project I'm currently working on.

The overhead bugs me a little, but it works. :-)

**Comment by StephanHoyer** [comment]
Ok, sold...

I take version 2.

Can you please rebase the PR on current master.

**Comment by maranomynet** [comment]
Done.
I guess we should be bumping the version number (0.2.0 ?) and npm publish

**Pull request merged**
