### PR TITLE
Add support for custom `pluralize` function.

### PR DESCRIPTION
**Pull request by maranomynet**
This is sorely needed for some languages.

### CODE REVIEW

**Comment by StephanHoyer** [comment]
That are insane pluralize rules. Icelandic is a cool language ;)

Just published it as 0.0.3 to npm.

Thanks!

**Comment by maranomynet** [comment]
Great.
Is this module available through npm?

**Comment by StephanHoyer** [comment]
yep, thats the reason for the fork

https://www.npmjs.com/package/translate.js

**Comment by maranomynet** [comment]
Nice. Google doesn't give it much juice I guess.

**Pull request merged**
