### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by StephanHoyer**

### CODE REVIEW

**Comment by StephanHoyer** [comment]
@maranomynet Would be great if you could review/merge this. I don't get the benchmark to run but I think this does not have performance implications. At least not to the bad.

**Comment by maranomynet** [comment]
I don't have time to run proper benchmarks on this, but this can't possibly be slower than the previous version.

It might even speed things up slightly - although I'm not sure it will be measurable. :-)

**Comment by StephanHoyer** [comment]
Can you look at the benchmark suite? does not seem to work or am I doing something wrong. Would be great to have a small tutorial how to run it in the readme though

**Comment by maranomynet** [comment]
Noted by #20

**Pull request merged**
